title: Taariqq's blog
author: taariqq
email: taariqq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The never ending blog!

# social links
twitter_username: taariqq
github_username:  taariqq

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
